project_name: 'deepfashion-fusion-CLIP-patch-learning-dino-last'
root_path: './dataset/deepfashion/'
device: [0]
phase: 'train'
disable_logger: false
mode: 'client'
port: 52162
batch_size: 80 #70
num_workers: 8
combiner_hidden_dim: 768  # large 768 base 512
img_pose_drop_rate: 0.1
lr: 0.0
accumulate_grad_batches: 1
scheduler_t0: 10
scheduler_t_mult: 2
scheduler_eta_max: 0.0001
scheduler_t_up: 3
scheduler_gamma: 0.5
temperature: 0.07
weight_decay: 0.001
max_epochs: 10
scale_size: [256, 256]
lambda_l1: 0.0001
encoder_type: 'dino' # 'clip'
attn_hidden_dim: 768  # large-1024 base 768
mh_attn_size: 16
img_encoder_update: true
trained_model_name: null
wandb_id: null
train_dataset_name: 'train_pairs_data.json'
test_dataset_name: 'test_pairs_data.json'
img_encoder_path: 'facebook/dinov2-base' # 'openai/clip-vit-base-patch16'
train_patch_embeddings: True
train_patch_embeddings_sampling_ratio: 0.01
