  project_name: 'deepfashion-diffusion-model-learning-dropmodule'
  root_path : './dataset/deepfashion/'
  phase: 'train'
  disable_logger: 'false'
  finetune_from: 'false'
  mode: 'client'
  port: 52162
  batch_size: 64
  num_workers: 8
  hidden_dim: 768
  lr: 0.0
  temperature: 0.07
  weight_decay: 0.001
  scheduler_t0: 40
  scheduler_t_mult: 2
  scheduler_eta_max: 0.0001
  scheduler_t_up: 5
  scheduler_gamma: 0.5
  max_epochs: 100
  data_root_path: './dataset/deepfashion'
  train_json_path: './dataset/deepfashion/train_pairs_data.json'
  test_json_path: './dataset/deepfashion/test_pairs_data.json'
  img_width: 256
  img_height: 256
  img_eval_size: [ 176, 256 ]  # (352, 512)
  guidance_scale: 2.0
  num_inference_steps: 20
  seed_number: 7
  num_images_per_prompt: 4
  test_n_samples: 10
  noise_offset: 0.1
  imgs_drop_rate: 0.1
  pose_drop_rate: 0.1
  src_image_encoder_path: 'openai/clip-vit-base-patch16'
  init_src_image_encoder: False
  fusion_image_encoder: True
  fusion_image_patch_encoder: True
  pretrained_model_name_or_path: 'stabilityai/stable-diffusion-2-1-base'
  fusion_model_path: '../sign-diff/logs/deepfashion-fusion-CLIP-patch-learning-0516/2024-05-16T11-06-54/last.ckpt'
  visualize_images: True
  calculate_metrics: True
  loss_type: 'mse_loss'  # mse_loss, shrinkage_loss
  shrinkage_a: 50
  shrinkage_c: 0.05
